"""empty message

Revision ID: 24fc24a46fd4
Revises: 57eb96f66e23
Create Date: 2015-05-09 20:01:09.716633

"""

# revision identifiers, used by Alembic.
revision = '24fc24a46fd4'
down_revision = '57eb96f66e23'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column(u'snippet', sa.Column('segment_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'snippet_ibfk_2', 'snippet', type_='foreignkey')
    op.create_foreign_key(None, 'snippet', 'segment', ['segment_id'], ['id'])
    op.drop_column(u'snippet', 'story_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'snippet', sa.Column('story_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'snippet', type_='foreignkey')
    op.create_foreign_key(u'snippet_ibfk_2', 'snippet', 'story', ['story_id'], ['id'])
    op.drop_column(u'snippet', 'segment_id')
    op.drop_table('segment')
    ### end Alembic commands ###
