"""empty message

Revision ID: 37a0209f435
Revises: 50ad4b1cc35c
Create Date: 2015-05-09 17:14:33.238028

"""

# revision identifiers, used by Alembic.
revision = '37a0209f435'
down_revision = '50ad4b1cc35c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippet', sa.Column('story_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'snippet', 'story', ['story_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'snippet', type_='foreignkey')
    op.drop_column('snippet', 'story_id')
    ### end Alembic commands ###
