"""empty message

Revision ID: 46d722187484
Revises: ce8d7e79e03
Create Date: 2015-05-10 03:27:32.290168

"""

# revision identifiers, used by Alembic.
revision = '46d722187484'
down_revision = 'ce8d7e79e03'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'name')
    ### end Alembic commands ###
