"""empty message

Revision ID: 57eb96f66e23
Revises: 37a0209f435
Create Date: 2015-05-09 19:43:02.091539

"""

# revision identifiers, used by Alembic.
revision = '57eb96f66e23'
down_revision = '37a0209f435'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'story', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story', type_='foreignkey')
    op.drop_column('story', 'user_id')
    ### end Alembic commands ###
