"""empty message

Revision ID: ce8d7e79e03
Revises: 24fc24a46fd4
Create Date: 2015-05-09 23:47:01.901471

"""

# revision identifiers, used by Alembic.
revision = 'ce8d7e79e03'
down_revision = '24fc24a46fd4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippet', sa.Column('is_first', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snippet', 'is_first')
    ### end Alembic commands ###
